version: '2.21.0'
services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
    ports:
      - "3306:3306"

    volumes:
      - db:/var/lib/mysql


  backend:
    depends_on:
      - mysqldb
    image: tasnimnaji99/tasnimnaji_5win_g1_pprojet3:tasnim
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
          "SPRING.DATASOURCE.URL": "jdbc:mysql://mysql:3306/tpachato?createDatabaseIfNotExist=true",
          "SPRING.DATASOURCE.USERNAME": "root",
          "SPRING.DATASOURCE.PASSWORD": null
          "SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "SPRING.JPA.HIBERNATE.DDL-AUTO" : "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db :

